Soluto/tweek

- services/editor/server/repositories/git-repository.js
- services/editor/server/repositories/keys-repository.js
> Git symlink

- services/editor/Dockerfile
- services/management/Dockerfile
> use clean images in last step

- services/management/src/rulesCache.js
- services/management/src/server.js
> 499 management rules cache

- README.md
- utils/generate_keys.sh
> Added a script to generate keys and updated README

- services/authoring/src/routes/search.js
- services/editor/server/common/perform-search.js
> optimize search

- services/editor/server/common/perform-search.js
> use query instead of search

- addons/Rules/Tweek.Drivers.Rules.Management/TweekManagementRulesDriver.cs
- services/management/src/rulesCache.js
- services/management/src/server.js
> 505 current version endpoint

- services/editor/server/repositories/git-repository.js
- services/editor/src/pages/keys/components/KeyPage/KeyEditPage/RevisionHistory/RevisionHistory.js
> fix history latest item behavior

- services/editor/src/services/search-service.js
- services/git-service/BareRepository/source/manifests/@tweek/editor/search/max_results.json
- services/git-service/BareRepository/tests-source/manifests/@tweek/editor/search/max_results.json
> make max search results count configurable

- e2e/selectors/keySelectors.js
- e2e/spec/keys/editKey.js
- e2e/utils/KeysPage.js
- services/editor/src/components/JPadFullEditor/JPadVisualEditor/Matcher/Properties/PropertyValue.js
- services/editor/src/components/JPadFullEditor/JPadVisualEditor/Matcher/Properties/styles.css
- services/editor/src/components/JPadFullEditor/JPadVisualEditor/Matcher/Properties/styles.less
- services/editor/src/services/types-service.js
> fix types-service value conversion

- e2e/spec/keys/editKey.js
- services/editor/src/services/operators-provider.js
> fix missing operators bug in editor

- .vscode/launch.json
- services/api/Tweek.ApiService.NetCore/Startup.cs
> add cors to swagger.json

- deployments/dev/docker-compose.override.yml
- e2e/integration/spec/authoring-api/add-app.test.js
- e2e/integration/spec/authoring-api/bulk-keys-upload.test.js
- services/api/Tweek.ApiService.NetCore/Controllers/DiagnosticsController.cs
- services/authoring/Dockerfile
- services/authoring/package.json
- services/authoring/src/server.js
- services/editor/Dockerfile
- services/editor/package.json
- services/editor/server/index.js
- services/editor/src/pages/settings/components/SettingsPage/SettingsPage.css
- services/editor/src/pages/settings/components/SettingsPage/SettingsPage.less
- services/management/Dockerfile
- services/management/package.json
- services/management/src/server.js
> 541 add health version endpoints

- services/editor/src/components/JPadFullEditor/JPadVisualEditor/Matcher/Properties/PropertyPredicate.js
- services/editor/src/components/JPadFullEditor/JPadVisualEditor/Matcher/Properties/PropertyValue.js
- services/editor/src/components/common/Input/TypedInput.js
> support types in 'in' operator

- e2e/ui/utils/Key.js
> 576 fixing ci failures

- addons/Context/Tweek.Drivers.Couchbase/BucketConnectionIsAlive.cs
- addons/Context/Tweek.Drivers.Couchbase/CouchBaseServiceAddon.cs
- addons/Context/Tweek.Drivers.Couchbase/Tweek.Drivers.Couchbase.csproj
> add caching to successful couchbase bucket connection checks

- services/editor/src/pages/keys/components/KeysList/KeysList.js
- services/editor/yarn.lock
- services/git-service/BareRepository/source/manifests/@tweek/editor/show_internal_keys.json
- services/git-service/BareRepository/tests-source/manifests/@tweek/editor/show_internal_keys.json
> Implemented hiding internal keys in the editor

- services/git-service/BareRepository/source/implementations/jpad/@tweek/editor/auth/@global/read_configuration.jpad
- services/git-service/BareRepository/source/implementations/jpad/@tweek/editor/auth/@global/write_context.jpad
- services/git-service/BareRepository/source/manifests/@tweek/editor/auth/@global/read_configuration.json
- services/git-service/BareRepository/source/manifests/@tweek/editor/auth/@global/write_context.json
- services/git-service/BareRepository/source/manifests/@tweek/editor/auth/tweek_editor_user/write_context.json
- services/git-service/BareRepository/tests-source/implementations/jpad/@tweek/editor/auth/@global/read_configuration.jpad
- services/git-service/BareRepository/tests-source/implementations/jpad/@tweek/editor/auth/@global/write_context.jpad
- services/git-service/BareRepository/tests-source/manifests/@tweek/editor/auth/@global/read_configuration.json
- services/git-service/BareRepository/tests-source/manifests/@tweek/editor/auth/@global/write_context.json
- services/git-service/BareRepository/tests-source/manifests/@tweek/editor/auth/tweek_editor_user/write_context.json
> Added default security authorization rules for tweek_editor_user

- services/editor/package.json
- services/editor/src/Routes.js
- services/editor/src/components/googleTagManager.js
- services/editor/yarn.lock
- services/git-service/BareRepository/source/implementations/jpad/@tweek/editor/google_tag_manager/enabled.jpad
- services/git-service/BareRepository/source/implementations/jpad/@tweek/editor/google_tag_manager/id.jpad
- services/git-service/BareRepository/source/manifests/@tweek/editor/google_tag_manager/enabled.json
- services/git-service/BareRepository/source/manifests/@tweek/editor/google_tag_manager/id.json
- services/git-service/BareRepository/tests-source/implementations/jpad/@tweek/editor/google_tag_manager/enabled.jpad
- services/git-service/BareRepository/tests-source/implementations/jpad/@tweek/editor/google_tag_manager/id.jpad
- services/git-service/BareRepository/tests-source/manifests/@tweek/editor/google_tag_manager/enabled.json
- services/git-service/BareRepository/tests-source/manifests/@tweek/editor/google_tag_manager/id.json
> Implemented google tag manager

- services/api/Tweek.ApiService.NetCore/Security/InternalAuthenticationProvider.cs
- services/api/Tweek.ApiService.NetCore/appsettings.json
- services/authoring/src/constants.ts
- services/editor/server/auth/generateToken.js
- services/editor/server/index.js
- services/git-service/BareRepository/init.sh
- services/management/src/repoValidator.js
- services/management/src/rulesCache.js
- services/management/src/server.js
> rsa keys from env vars

- services/api/Tweek.ApiService.NetCore/Tweek.ApiService.NetCore.csproj
- services/authoring/package.json
- services/editor/package.json
- services/management/package.json
> Bump versions

- services/api/Tweek.ApiService.NetCore/Controllers/ContextController.cs
- services/api/Tweek.ApiService.NetCore/Controllers/DiagnosticsController.cs
- services/api/Tweek.ApiService.NetCore/Controllers/KeysController.cs
closes #425 
fix and closes #569
> some minor improvements in swagger

- addons/Rules/Tweek.Drivers.Blob/BlobRulesDriver.cs
- core/Engine/Engine.Drivers/Rules/IRulesDriver.cs
- core/Engine/Engine.Tests/TestDrivers/InMemoryTestDriver.cs
- services/api/Tweek.ApiService.NetCore/Controllers/KeysController.cs
- services/api/Tweek.ApiService.NetCore/Controllers/RepoVersionController.cs
- services/api/Tweek.ApiService.NetCore/Security/CorsExtensions.cs
- services/api/Tweek.ApiService.SmokeTests/ContextTests.cs
- services/api/Tweek.ApiService.SmokeTests/CorsTests.cs
- services/api/Tweek.ApiService.SmokeTests/ITweekApi.cs
- services/api/Tweek.ApiService.SmokeTests/RepositoryVersionTests.cs
- services/api/Tweek.ApiService.SmokeTests/SwaggerTests.cs
- services/api/Tweek.ApiService.SmokeTests/TweekApiServiceFactory.cs
> Add repo-version endpoiont to Api

- services/editor/src/components/JPadFullEditor/JPadTextEditor/JPadTextEditor.js
> Fix source tab regression

- CI/run_tests.sh
- TweekApiSmokeTestDockerfile
- deployments/dev/zap/glue/Dockerfile
- deployments/dev/zap/glue/run_glue.sh
- deployments/dev/zap/glue/test.sh
- e2e/ui/Dockerfile
- e2e/ui/test.sh
- e2e/ui/utils/client-utils.js
- services/api/Tweek.ApiService.SmokeTests/test.sh
https://github.com/Soluto/tweek/pull/653#issuecomment-344277847
> wait for scanning to finish

- services/editor/server/auth/httpDigest.js
> add AUTH_DIGEST_CREDENTIALS for user:pass pairs

- services/authoring/src/routes/search.ts
- services/authoring/src/search-index/build/build.js
> Made search case insensitive #goodnessSquad

- services/management/package.json
- services/management/src/object-storage.js
> check if versions file exists even if bucket is created

- services/authoring/package.json
- services/authoring/src/repositories/git-repository.ts
> remove `--follow` option from `git log`

- services/api/Tweek.ApiService/Startup.cs
- services/api/Tweek.ApiService/Tweek.ApiService.csproj
> Added Prometheus support to api

- e2e/ui/spec/keys/edit-key.js
- e2e/ui/utils/Key.js
- services/editor/src/components/JPadFullEditor/JPadFullEditor.js
- services/editor/src/components/JPadFullEditor/JPadTextEditor/JPadTextEditor.js
> Remove insert changes button from JPad text Editor

- services/editor/src/components/JPadFullEditor/JPadVisualEditor/Matcher/Properties/Avatar.js
- services/editor/src/components/JPadFullEditor/JPadVisualEditor/Matcher/Properties/styles.css
- services/editor/src/components/JPadFullEditor/JPadVisualEditor/Matcher/Properties/styles.less
> added tooltip to avatar

- core/Engine/Tweek.Engine.Tests/Tweek.Engine.Tests.csproj
- core/JPad/Tweek.JPad.Utils/Tweek.JPad.Utils.csproj
- services/api/Tweek.ApiService.SmokeTests/Tweek.ApiService.SmokeTests.csproj
- services/api/Tweek.ApiService/Tweek.ApiService.csproj
> Upgrade jpad

- e2e/integration/spec/tweek-api/value-distribution.test.js
- e2e/ui/spec/keys/multi-variant.js
- e2e/ui/utils/Rule.js
- services/editor/package.json
- services/editor/spec/unit/utils/mutator-spec.js
- services/editor/src/components/JPadFullEditor/JPadVisualEditor/RuleValue/RuleValue.js
- services/editor/src/components/JPadFullEditor/rules-utils.js
- services/editor/src/components/common/CustomSlider/CustomSlider.css
- services/editor/src/components/common/CustomSlider/CustomSlider.js
- services/editor/src/components/common/CustomSlider/CustomSlider.less
- services/editor/src/components/common/Input/TypedInput.js
- services/editor/src/pages/keys/components/KeyPage/KeyAddPage/KeyValueTypeSelector/KeyValueTypeSelector.js
- services/editor/src/utils/mutator.js
- services/git-service/BareRepository/tests-source/implementations/jpad/integration_tests/value_distribution/array_format.jpad
- services/git-service/BareRepository/tests-source/implementations/jpad/integration_tests/value_distribution/object_format.jpad
- services/git-service/BareRepository/tests-source/manifests/integration_tests/value_distribution/array_format.json
- services/git-service/BareRepository/tests-source/manifests/integration_tests/value_distribution/object_format.json
> Support objects in multivariant args

- services/publishing/Dockerfile
- services/publishing/Tweek.Publishing.Service/Startup.cs
> hack for fixing sshd defunct processes

- services/editor/src/pages/keys/components/KeysList/DirectoryTreeView.js
> add sorting which put trees before leaf nodes

- services/api/Tweek.ApiService/Program.cs
- services/api/Tweek.ApiService/Startup.cs
- services/api/Tweek.ApiService/Tweek.ApiService.csproj
- services/api/Tweek.ApiService/appsettings.json
- services/authoring/src/constants.ts
- services/authoring/src/repositories/git-continuous-updater.ts
- services/authoring/src/repositories/git-repository.ts
- services/authoring/src/routes/keys.ts
- services/authoring/src/routes/search.ts
- services/authoring/src/search-index/index.ts
- services/authoring/src/server.ts
- services/authoring/src/utils/jsonLogger.ts
- services/authoring/src/utils/transactor.ts
- services/authoring/yarn.lock
- services/publishing/Tweek.Publishing.Service/Program.cs
- services/publishing/Tweek.Publishing.Service/Startup.cs
- services/publishing/Tweek.Publishing.Service/Tweek.Publishing.Service.csproj
- services/publishing/Tweek.Publishing.Service/appsettings.json
> JSON logging

- services/secure-gateway/security/authentication.go
- services/secure-gateway/security/jwkCache.go
> Implemented JWK cache

- e2e/integration/spec/authoring-api/test-data/policy.csv
- e2e/integration/spec/authoring-api/write-validation.spec.js
- e2e/integration/spec/secure-gateway/v2.spec.js
- e2e/integration/utils/manifest.js
- e2e/integration/utils/utils.js
> e2e integration tests for api v2

- services/gateway/Gopkg.lock
- services/gateway/main.go
- services/gateway/metrics/metrics.go
- services/gateway/passThrough/passThrough.go
> Added metrics per upstream for passthrough

- services/publishing/Dockerfile
- services/publishing/Tweek.Publishing.Service/Handlers/PushHandler.cs
- services/publishing/Tweek.Publishing.Service/Startup.cs
- services/publishing/Tweek.Publishing.Service/Sync/Converters/ExtractorRulesConverter.cs
- services/publishing/Tweek.Publishing.Service/Sync/Converters/SubjectExtractionRulesConverter.cs
- services/publishing/Tweek.Publishing.Service/Validation/Patterns.cs
- services/publishing/Tweek.Publishing.Service/Validation/SubjectExtractionRulesValidationException.cs
- services/publishing/Tweek.Publishing.Service/Validation/SubjectExtractionValidator.cs
- services/publishing/Tweek.Publishing.Tests/Validation/SubjectExtractionValidatorTests.cs
> 862 - Publishing validates sub extraction rules while sync to minio

- core/Engine/Tweek.Engine.Drivers/Context/SchemaValidation.cs
- core/Engine/Tweek.Engine.Tests/Context/InputValidationContextDriverTests.cs
- core/Engine/Tweek.Engine.Tests/Context/schema.json
- services/api/Tweek.ApiService/Tweek.ApiService.csproj
fix string comparison in schema validation
Improved logging
> fix string comparison in schema validation

- services/editor/spec/unit/services/context-service-spec.js
- services/editor/src/components/JPadFullEditor/JPadVisualEditor/Matcher/Matcher.js
- services/editor/src/components/JPadFullEditor/JPadVisualEditor/Matcher/Properties/PropertyName.js
- services/editor/src/components/JPadFullEditor/JPadVisualEditor/Partition/PartitionsSelector.js
- services/editor/src/components/JPadFullEditor/JPadVisualEditor/PartitionsList/PartitionsList.js
- services/editor/src/services/context-service.js
> added system.time_utc to editor

- addons/Context/Tweek.Drivers.Context.Couchbase/BucketConnectionHealthCheck.cs
- addons/Context/Tweek.Drivers.Context.Couchbase/CouchBaseServiceAddon.cs
- addons/Context/Tweek.Drivers.Context.Couchbase/Tweek.Drivers.Context.Couchbase.csproj
- services/api/Tweek.ApiService/Tweek.ApiService.csproj
> Improved couchbase healthcheck by adding latency check

- services/editor/package.json
- services/editor/src/components/JPadFullEditor/JPadVisualEditor/Matcher/Properties/PropertyPredicate.js
- services/editor/src/pages/settings/components/IdentityPage/IdentityProperty/IdentityProperty.js
Small fixes in the editor in edge cases: deleting matchers with complex types (like version) and creating properties of complex types
> Fix editor bugs

- e2e/integration/spec/gateway/v2.spec.js
- services/gateway/security/authentication.go
- services/git-service/BareRepository/source/policy.json
- services/git-service/BareRepository/tests-source/policy.json
> Implemented anonymous access

- deployments/dev/docker-compose.e2e.yml
- e2e/ui/spec/keys/edit-key.js
- services/editor/package.json
- services/editor/src/components/JPadFullEditor/JPadVisualEditor/Matcher/Properties/PropertyValue.js
- services/editor/src/components/common/Input/Calendar.css
- services/editor/src/components/common/Input/Calendar.less
- services/editor/src/components/common/Input/DateInput.css
- services/editor/src/components/common/Input/DateInput.js
- services/editor/src/components/common/Input/DateInput.less
- services/editor/src/components/common/Input/Input.js
- services/editor/src/components/common/Input/TypedInput.js
- services/editor/yarn.lock
- services/git-service/BareRepository/tests-source/manifests/behavior_tests/edit_key/visual/const/date_type.json
> Implemented date picker

- services/gateway/metrics/metrics.go
> Added percentile 75 and 95 to gateway

- services/gateway/authorization.rego
- services/gateway/testdata/policy.json
- services/gateway/testdata/test_authorization.rego
> Implemented wildcard context

- services/editor/src/pages/keys/components/KeysList/TreeView/TreeDirectory.js
>  add tooltip to add key in folder

- services/editor/src/components/common/Input/DateInput.css
- services/editor/src/components/common/Input/DateInput.less
> Fixed less for datepicker

- services/editor/package.json
- services/editor/src/services/auth-service.js
- services/editor/yarn.lock
> Added token expiration check in isAuthenticated

- services/editor/src/pages/keys/components/KeysList/KeysList.css
- services/editor/src/pages/keys/components/KeysList/KeysList.js
- services/editor/src/pages/keys/components/KeysList/KeysList.less
> Fix keys alignment in navigation

- services/gateway/appConfig/appConfig.go
- services/gateway/main.go
- services/gateway/security/authentication.go
- services/gateway/security/subjectExtractor.go
- services/gateway/security/userinfo.go
> Impelmented userinfo endpoint

- services/api/Tweek.ApiService/Tweek.ApiService.csproj
- services/publishing/Tweek.Publishing.Service/Tweek.Publishing.Service.csproj
> Updated  Microsoft.AspNetCore.App to version 2.1.5

- services/gateway/main.go
- services/gateway/router.go
> Added /configurations endpoint

- services/gateway/main.go
- services/gateway/passThrough/passThrough.go
> Refactored passThrough

- e2e/integration/spec/authoring-api/test-data/policy.json
- services/editor/src/components/googleTagManager.js
- services/editor/src/pages/keys/components/KeysList/KeysList.js
- services/editor/src/services/search-service.js
- services/editor/src/store/ducks/selectedKey.js
- services/editor/src/utils/fetch.js
- services/git-service/BareRepository/source/security/policy.json
- services/git-service/BareRepository/tests-source/security/policy.json
> Added editor context to requests for configuration

- services/gateway/security/authentication.go
> Fixed name and email extraction in gateway

- services/gateway/security/authentication.go
> Removed anonymous from name and email

- services/publishing/Tweek.Publishing.Service/Startup.cs
> Fixed stale revision checking

- e2e/integration/spec/gateway/v2.spec.js
- services/gateway/appConfig/appConfig.go
- services/gateway/security/authorizer.go
- services/gateway/settings/settings.json
- services/gateway/transformation/transformation.go
- services/gateway/transformation/transformation_test.go
> Implemented keyPath transformation

- e2e/integration/spec/gateway/v2_cors.spec.js
- services/gateway/Gopkg.lock
- services/gateway/Gopkg.toml
- services/gateway/handlers/statusHandler.go
- services/gateway/main.go
> Added repo revision to status

- services/gateway/Dockerfile
- services/gateway/main.go
- services/gateway/swagger.go
- services/gateway/swagger.yml
> Fixed swagger.yml

- .gitattributes
> Windows: Set the git hooks of publisher to use eol=lf

- services/publishing/Tweek.Publishing.Service/Sync/StorageSynchronizer.cs
> Fixed StaleRevisionException being thrown when there is another problem

- services/publishing/Tweek.Publishing.Service/Handlers/PushHandler.cs
- services/publishing/Tweek.Publishing.Service/Handlers/SyncHandler.cs
- services/publishing/Tweek.Publishing.Service/Handlers/ValidationHandler.cs
- services/publishing/Tweek.Publishing.Service/Program.cs
- services/publishing/Tweek.Publishing.Service/Startup.cs
- services/publishing/Tweek.Publishing.Service/Sync/StorageSynchronizer.cs
- services/publishing/Tweek.Publishing.Service/Tweek.Publishing.Service.csproj
> Added metrics to publishing

- services/editor/package.json
- services/editor/src/PrivateRoute.js
- services/editor/src/services/auth-service.js
- services/editor/yarn.lock
> Fixed silent token refresh issue

- services/editor/public/manifest.json
https://developers.google.com/web/fundamentals/web-app-manifest/
> Change editor's name from React App to Tweek in manifest.json

- services/publishing/Tweek.Publishing.Service/Startup.cs
- services/publishing/Tweek.Publishing.Service/Sync/RevisionException.cs
- services/publishing/Tweek.Publishing.Service/Sync/StorageSynchronizer.cs
> Fixed stale revision issue

- services/gateway/security/jwkCache.go
> Refreshing JWKs when key is missing

- services/gateway/security/requestUtils.go
- services/gateway/security/requestUtils_test.go
> Fixed read for context in gateway

- services/editor/src/services/auth-service.js
> Fixed login expiration

- services/editor/src/services/auth-service.js
> Fixed redirect after login

- CI/codefresh.yml
- services/api/Tweek.ApiService/Tweek.ApiService.csproj
- services/authoring/package.json
- services/editor/package.json
- services/gateway/version.go
- services/publishing/Tweek.Publishing.Service/Tweek.Publishing.Service.csproj
> bumped major version for all services

- services/gateway/appConfig/appConfig.go
- services/gateway/version.go
> Made gateway start even if gateway.json is not present

- services/gateway/Gopkg.lock
- services/gateway/Gopkg.toml
- services/gateway/appConfig/appConfig.go
- services/gateway/audit/logAuditor.go
- services/gateway/externalApps/externalApps.go
- services/gateway/handlers/statusHandler.go
- services/gateway/main.go
- services/gateway/passThrough/passThrough.go
- services/gateway/security/authRouter.go
- services/gateway/security/authentication.go
- services/gateway/security/authorization.go
- services/gateway/security/authorizer.go
- services/gateway/security/jwkCache.go
- services/gateway/security/jwtUtils.go
- services/gateway/security/subjectExtractor.go
- services/gateway/security/userinfo.go
- services/gateway/setup.go
- services/gateway/swagger.go
- services/gateway/transformation/health.go
- services/gateway/transformation/transformation.go
> Using logrus for logging instead of the default golang log in gateway

- services/gateway/Dockerfile
- services/gateway/go.sum
- services/gateway/main.go
- services/gateway/swagger.go
- services/gateway/swagger/openapi.yaml
- services/gateway/swagger/swagger.yml
2. openapi is needed for free-form params such as http://tweek-domain/values/some_key?**user=john**&**company=soluto**
> openapi support

- services/editor/src/store/ducks/notifications.js
- services/editor/src/utils/tweekClients.js
>  fixed tweek-management client timeout and format properly fetchError

- utils/generate_keys.sh
Added code to output basic auth password after keys generation
> Added code to output basic auth password after keys generation

- TweekApi.Dockerfile
- services/api/Tweek.ApiService/Tweek.ApiService.csproj
- services/authoring/package.json
- services/authoring/yarn.lock
- services/publishing/Dockerfile
- services/publishing/Tweek.Publishing.Service/Tweek.Publishing.Service.csproj
Made uid of user git equal 1000, so it's predictable for scripting, side containers etc.
> Made uid of user git equal 1000

- services/gateway/security/authRouter.go
- services/gateway/security/authentication.go
- services/gateway/security/jwtUtils.go
- services/gateway/version.go
> Fixed improper handling of pkcs8 in gateway

- services/editor/src/services/auth-service.js
> fix basic auth expiration behavior

- services/authoring/package.json
- services/authoring/src/constants.ts
> Update node copy file sync

- docs/webhooks/webhooks.md
- services/editor/src/Routes.js
- services/editor/src/components/common/index.js
- services/editor/src/pages/keys/components/KeyPage/KeyEditPage/KeyEditPage.js
- services/editor/src/pages/keys/components/KeyPage/KeyEditPage/KeyEditPage.less
- services/editor/src/pages/settings/components/HooksPage/EditHookPage.js
- services/editor/src/pages/settings/components/HooksPage/EditHookPage.less
- services/editor/src/pages/settings/components/HooksPage/HookTypes.js
- services/editor/src/pages/settings/components/HooksPage/HooksPage.js
- services/editor/src/pages/settings/components/HooksPage/HooksPage.less
- services/editor/src/pages/settings/components/PoliciesPage/RemoteCodeEditor.js
- services/editor/src/pages/settings/components/PoliciesPage/acl-schema.json
- services/editor/src/pages/settings/components/PoliciesPage/utils.js
- services/editor/src/pages/settings/components/SettingsPage/SettingsPage.js
- services/editor/src/store/ducks/index.js
- services/editor/src/store/ducks/notifications.js
- services/editor/src/utils/debounce.js
- services/editor/src/utils/index.js
- services/editor/src/utils/useErrorNotifier.js
Allows setting hooks on keys (including the `*` wildcard). Only notification webhooks are supported at this time.  
Paths for hooks implicitly start after the `implementations`/`manifests` prefixes.
Hooks can be edited in the settings page, under the `Hooks` entry in the menu.
There are also links from the key page to create or view hooks for this key.
Centralized storage in a JSON file at the git repo. Format:
```JSON
[
{
"id": "auto_generated_uid",
"keyPath": "path/to/key",
"type": "notification_webhook",
"url": "http://some-domain/awesome_hook"
},
{
"id": "auto_generated_uid",
"keyPath": "wildcard/path/*",
"type": "notification_webhook",
"url": "http://some-other-domain/another_awesome_hook"
}
]
```
All GET APIs return an `ETag` header and all POST/PUT/DELETE APIs can optionally accept …
> Notification webhooks frontend

- docs/webhooks/webhooks.md
- services/editor/package.json
- services/editor/src/store/ducks/notifications.js
- services/publishing/Tweek.Publishing.Service/Helpers/HooksHelper.cs
- services/publishing/Tweek.Publishing.Service/Tweek.Publishing.Service.csproj
- services/publishing/Tweek.Publishing.Tests/Helpers/HooksHelperTests.cs
Also resolves #1123 by setting UI errors to disappear after 15 seconds
> hooks - handle different implementation types

- CI/codefresh.yml
Adding explicit gi-clone step to codefresh.yml
> adding git-clone step to codefresh.yml

- README.md
fixed some spelling errors in the file
> fix(docs): Update README.md - fix spelling

- core/Engine/Tweek.Engine.Drivers/Context/SchemaValidation.cs
- core/Engine/Tweek.Engine.Tests/Context/InputValidationContextDriverTests.cs
- core/Engine/Tweek.Engine.Tests/Context/schema.json
- services/api/Tweek.ApiService/Tweek.ApiService.csproj
> fix custom/array types validation handling in context writes

- services/gateway/security/jwkCache.go
reload happens in the background, no performance impact
> [tweek-gateway] reload jwk keys on error

- core/Utils/JsonValueConverter.Tests/NativeJsonValueConverterTests.cs
- core/Utils/JsonValueConverter.Tests/NewtonsoftJsonValueConverterTests.cs
- core/Utils/JsonValueConverter/JsonValueConverter.csproj
- core/Utils/JsonValueConverter/NativeJsonValueConverter.cs
- core/Utils/JsonValueConverter/NewtonsoftJsonValueConverter.cs
- e2e/integration/spec/gateway/v2.spec.js
- e2e/integration/spec/tweek-api/context.test.js
- services/api/Tweek.ApiService/Controllers/ContextController.cs
- services/api/Tweek.ApiService/Controllers/KeysController.cs
- services/api/Tweek.ApiService/Startup.cs
- services/api/Tweek.ApiService/Tweek.ApiService.csproj
Commit messages for more details
> Use System.Text.Json instead of Newtonsoft in MVC serialization

- e2e/integration/spec/authoring-api/apps.spec.js
- services/authoring/package.json
- services/authoring/src/apps/apps-utils.ts
- services/authoring/src/repositories/apps-repository.ts
- services/authoring/src/routes/apps.ts
- services/authoring/src/security/strategies/app-credentials.ts
- services/authoring/src/utils/app-utils.ts
- services/authoring/test/repositories/apps-repository.spec.ts
- services/gateway/security/requestUtils_test.go
- services/gateway/settings/settings.json
- services/gateway/version.go
> External apps management improved

- e2e/integration/spec/gateway/v2.spec.js
- services/authoring/src/routes/apps.ts
> More data at GET external apps endpoint

- .github/workflows/versions_to_deploy.sh
https://github.com/actions/toolkit/issues/641
> Replace set-env command in github ci

- services/editor/package.json
- services/editor/src/components/alerts/Alerts.js
- services/editor/src/components/alerts/Alerts.less
- services/editor/src/components/common/Input/EditJSON.js
* Make json key editor resizable
* bump editor version to rc19
> Make json key editor resizable (#1372)

- services/gateway/go.mod
- services/gateway/go.sum
- services/gateway/security/requestUtils.go
- services/gateway/security/requestUtils_test.go
- services/gateway/version.go
- services/git-service/BareRepository/tests-source/security/policy.json
[CORE-786](https://soluto.atlassian.net/browse/CORE-786)
-Make the hooks readable only by authenticated users
> fix: make hooks readable with auth only [CORE-786]
